---
version: "3.4"

services:
  dev:
    build:
      context: .
      target: development
    image: todo-app:dev
    container_name: todo-app-dev
    ports:
      - "8080:80"
    volumes:
      - ${PWD-.}:/home/app

  test:
    build:
      context: .
      target: test
    image: todo-app:test
    container_name: todo-app-test
    volumes:
      - ${PWD-.}:/home/app
