[tool.poetry]
name = "to-do-app"
version = "1.0.0"
description = "A simple to-do app"
authors = []

[tool.poetry.dependencies]
certifi==2020.6.20
chardet==3.0.4
click==7.1.2
Flask==1.1.1
idna==2.10
itsdangerous==1.1.0
Jinja2==2.11.2
MarkupSafe==1.1.1
oauthlib==3.1.0
py-trello==0.16.0
python-dateutil==2.8.1
python-dotenv==0.12.0
pytz==2020.1
requests==2.24.0
requests-oauthlib==1.3.0
six==1.15.0
urllib3==1.25.9
Werkzeug==1.0.1